text = str(input('Digite um texto qualquer: ')).lower().strip()
qty = text.count('a')
first = text.find('a')
last = text.rfind('a')
print('A letra \'A\' aparece {} vezes'.format(qty))
print('A letra \'A\' aparece pela primeira vez na posição {}'.format(first+1))
print('A letra \'A\' aparece pela última vez na posição {}'.format(last+1))